name: CD

on:
  push:
    branches: main

jobs:
  build:
    name: build pos-system-backend
    runs-on: ubuntu-latest
    steps:
#      - name: Clear useless artifacts
#        uses: c-hive/gha-remove-artifacts@v1.2.0
#        with:
#          age: '14 days'

      - uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: |
          
          dotnet publish -c Release --property PublishDir='${{ github.workspace }}/site' -r win-x64 --self-contained false
      - name: Zip Package
        run: |
          cd ${{ github.workspace }}/site
          zip -r ${{ github.workspace }}/site.zip *
      - name: Upload zip sources
        uses: actions/upload-artifact@v2
        with:
          name: pos-system-backend
          path: site.zip

  deploy:
    needs: build
    name: deploy pos-system-backend
    runs-on: self-hosted
    steps:
      - name: Clone source zip
        uses: actions/download-artifact@v2
        with:
          name: pos-system-backend
      - name: Deploy to IIS
        shell: powershell
        run: |
          iisreset /stop
          Remove-Item -Recurse -Force -Confirm:$false D:\web-folder\
          mkdir D:\web-folder
          Expand-Archive site.zip D:\web-folder
          iisreset /start

